#Assignment 1: perform EDA on alcgp and ncontrols (esoph dataset)

dim(esoph)
attach(esoph)
head(esoph)
alcgp
is.numeric(alcgp)
is.character(alcgp)
is.double(alcgp)
is.factor(alcgp)
str(alcgp)
summary(alcgp)
table.alcgp <- table(alcgp)
table.alcgp
barplot(table.alcgp, main = "Alcgp barplot")
names(table.alcgp)
levels(alcgp)


str(ncontrols)
summary(ncontrols)
boxplot(ncontrols)
mean(ncontrols)
median(ncontorls)
mode(ncontrols)
var(ncontrols)
sqrt(var(ncontrols))
range(ncontrols)
length(ncontrols)
quantile(ncontrols, p = c(.25, .5, .75) )
hist(ncontrols)
hist(ncontrols, freq = F)
lines(density(ncontrols), lwd = 5, col = "red")
detach(esoph)
#Assignment 2: perform EDA on dataset "Tree"

attach(trees)
dim(trees)
head(trees)
tail(trees)
summary(trees)
str(trees)
hist(Girth, freq = F)
lines(density(Girth), lwd = 2, col = "blue")
hist(Height, freq = F)
lines(density(Height), lwd = 2, col = "blue")
hist(Volume, freq = F)
lines(density(Volume), lwd = 2, col = "blue")
boxplot(trees)
pairs(trees)
detach(trees)
#Assignment 3: Do EDA on stackloss (Do explantory and response stuff)
attach(stackloss)
head(stackloss)
tail(stackloss)
str(stackloss)
summary(stackloss)
plot(stackloss)
pairs(stackloss)
plot(stack.loss, Air.Flow)
plot(stack.loss, Water.Temp)
plot(stack.loss, Acid.Conc.)
cor(stackloss)
library(corrplot)
corrplot(cor(stackloss), method = "number")
